### PR TITLE
fix(avatar): wrong avatar styling

### LINKED ISSUE #4304: Why are there some very tiny borders around the Avatar?
### Description

When I am using the Avatar component and refresh the page several times, there is a high probability that a very small border color will appear around the avatar. However, when I add a little style to the Avatar component, the small border above Disappeared!

### Link to Reproduction

https://codesandbox.io/s/condescending-bogdan-tuse5?file=/src/App.js

### Steps to reproduce

1. Enter the page to carefully observe whether there is a small frame, if it does not appear, refresh the page several times, if it still does not appear, refresh the codesendbox, so that it can be reproduced! It seems that this component of the official website also has this problem! You have to be very careful to see this subtle difference!

### Chakra UI Version

1.6.4

### Browser

_No response_

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

image
Take a closer look at the border in the picture above. Are there any very subtle colors?

But if I refresh the page many times, this very subtle border may disappear. Look at the picture below. Does anyone know what the problem is? ?

image

### PR DESCRIPTION
**Pull request by anubra266**
Fixes #4304
Fix issue where background remained after image is loaded

### CODE REVIEW

File: packages/components/avatar/src/avatar.tsx [hunk 1]
```diff
@@ -61,6 +65,11 @@ export const Avatar = forwardRef<AvatarProps, "span">((props, ref) => {
     ...rest
   } = omitThemingProps(props)
 
+  const onLoad: UseImageProps["onLoad"] = (e) => {
+    runIfFn(onLoad, e)
+    setIsLoaded(true)
+  }
+
```
Comment (segunadebayo) [inline packages/components/avatar/src/avatar.tsx:72]: You can make this more concise by passing it directly to the onLoad prop

```suggestion
  const onLoad = callAllHandlers(onLoad, () => {
    setIsLoaded(true)
  })
```

File: packages/components/theme/src/components/avatar.ts [hunk 2]
```diff
@@ -35,7 +35,9 @@ const baseStyleContainer = defineStyle((props) => {
   const borderColor = mode("white", "gray.800")(props)
 
   return {
-    bg,
+    "&:not([data-loaded])": {
+      bg,
+    },
```
Comment (segunadebayo) [inline packages/components/theme/src/components/avatar.ts:40]: Please use a css-var here. In case a user is already overriding the bg from the theme.

Assign the value to a CSS var and use `bg: $avatarBg.reference` at the root.

File: packages/components/avatar/src/avatar.tsx [hunk 3]
```diff
@@ -61,6 +65,9 @@ export const Avatar = forwardRef<AvatarProps, "span">((props, ref) => {
     ...rest
   } = omitThemingProps(props)
 
+  const onLoad = callAllHandlers(onLoad, () => {
```
Comment (segunadebayo) [inline packages/components/avatar/src/avatar.tsx:68]: Can you put this inline (directly in the onLoad prop below?

File: packages/components/theme/src/components/avatar.ts [hunk 4]
```diff
@@ -35,7 +37,9 @@ const baseStyleContainer = defineStyle((props) => {
   const borderColor = mode("white", "gray.800")(props)
 
   return {
-    bg,
+    "&:not([data-loaded])": {
+      bg: $avatarBg.reference,
+    },
```
Comment (segunadebayo) [inline packages/components/theme/src/components/avatar.ts:42]:
```suggestion
    bg: $avatarBg.reference,
    "&:not([data-loaded])": {
      [$avatarBg.variable]: bg,
    },
```

File: packages/components/theme/src/components/avatar.ts [hunk 5]
```diff
@@ -24,6 +24,8 @@ const baseStyleExcessLabel = defineStyle((props) => {
   }
 })
 
+const $avatarBg = cssVar("avatar-background")
+
 const baseStyleContainer = defineStyle((props) => {
   const { name, theme } = props
   const bg = name ? randomColor({ string: name }) : "gray.400"
```
Comment (segunadebayo) [inline packages/components/theme/src/components/avatar.ts:31]:
```suggestion
  const bg = name ? randomColor({ string: name }) : "colors.gray.400"
```
