### PR TITLE
fix(media-query): create media queries using breakpoint name keys only

### LINKED ISSUE #1444: [useBreakpoint/useBreakpointValue] API partially broken
As reported on [Discord](https://canary.discordapp.com/channels/660863154703695893/660865137137156146/737974879168757830), the return value of `useBreakpoint` and `useBreakpointValue` is `undefined` if no matching breakpoint is currently active; it should fallback to `base` if given.

Also, the passed argument must currently match array indices:
`{base: 'column', 0: 'column', 1: 'row', 2: 'row', 3: 'row'}`
 instead of, following the docs, 
`{base: 'column', sm: 'column', md: 'row', lg: 'row', lg: 'row'}`.

It's also broken in the [docs](https://next.chakra-ui.com/docs/hooks/use-breakpoint-value); `variant` is always `undefined` according to the devtools:

image

https://codesandbox.io/s/distracted-bird-3ifkq?file=/src/App.tsx

**Expected Behavior** API works as expected.

**Suggested solution(s)**

Investigate what goes wrong [here](https://github.com/chakra-ui/chakra-ui/blob/c38892760257b9bbf1b63c05f7f9ccf1684a90b0/packages/media-query/src/use-breakpoint-value.ts#L15).

### PR DESCRIPTION
**Pull request by with-heart**
Fixes #1444 

This PR resolves an issue where `createMediaQueries` was returning a broken breakpoints array, causing `useBreakpointValue` objects to only match when using array numbers as keys rather than the breakpoint names.

Also added tests for both `createMediaQueries` and `useBreakpointValue` to help us avoid this situation in the future.

Thanks to @nassimbenkirane for investigating and sharing what he found!

### CODE REVIEW

File: packages/media-query/src/create-media-query.ts [hunk 1]
```diff
@@ -1,12 +1,17 @@
...
  * using a combination of `min-width` and `max-width`.
  */
 function createMediaQueries(breakpoints: Dict) {
-  const sorted = getSortedKeys(breakpoints)
+  // get the non-number breakpoint keys from the provided breakpoints
+  const keys = Object.keys(breakpoints)
+
+  // use only the keys matching the official breakpoints names, and sort them in
+  // largest to smallest order
+  const sorted = bps.filter((bp) => keys.includes(bp)).reverse()
```
Comment (with-heart) [inline packages/media-query/src/create-media-query.ts:14]: Instead of using all of the keys that are on `breakpoints` args (which includes stringified array indexes since it'll be an array with keys attached to its prototype), we instead use the `breakpoints` array from `@chakra-ui/utils` and only include keys that are present in the object passed to the function. 

This guarantees that we're only using valid breakpoints, and that we're using the actual breakpoint names.

We also reverse them to make sure we're returning an array of largest to smallest breakpoints.

File: packages/media-query/src/create-media-query.ts [hunk 2]
```diff
@@ -1,12 +1,17 @@
...
 import calculateMeasurement from "calculate-measurement"
 
 /**
  * Create a media query string from the breakpoints,
  * using a combination of `min-width` and `max-width`.
  */
 function createMediaQueries(breakpoints: Dict) {
-  const sorted = getSortedKeys(breakpoints)
+  // get the non-number breakpoint keys from the provided breakpoints
+  const keys = Object.keys(breakpoints)
```
Comment (nassimbenkirane) [inline packages/media-query/src/create-media-query.ts:10]: I see that there was an import of objectKeys function, wonder what is different from Object.keys (maybe some polyfills ?) But it might be worth using it here ?

Comment (with-heart) [reply packages/media-query/src/create-media-query.ts:10]: It was solely for wrapping `Object.keys` with more accurate types which we're not using here, so I think we're good!
