### PR TITLE
fix(system): set default useStyleConfig arguments

### LINKED ISSUE #2705: useStyleConfig without props throws
# Bug report

## Describe the bug

`useStyleConfig` allows passing undefined as `props` but the code relies on the presence of this parameter.

## To reproduce

`useStyleConfig('MyComponent')`

## Minimal reproduction

https://codesandbox.io/s/restless-sound-jiq50?file=/src/App.tsx

## Expected behavior

`props` should either have a sane fallback or be typed correctly

## Additional context

typedef: https://github.com/chakra-ui/chakra-ui/blob/develop/packages/system/src/use-style-config.ts#L22
destructuring: https://github.com/chakra-ui/chakra-ui/blob/develop/packages/system/src/use-style-config.ts#L27

### PR DESCRIPTION
**Pull request by with-heart**
Fixes #2705

`useStyleConfig` is typed for the `props` argument to be optional, but
we then destructure `props` within the function. This change resolves
the issue by setting a default empty object value for the `props` and
`opts` arguments.

### CODE REVIEW

File: packages/system/src/use-style-config.ts [hunk 1]
```diff
@@ -23,7 +23,7 @@ export function useStyleConfig(
   opts?: { isMultiPart?: boolean },
 ): SystemStyleObject
 
-export function useStyleConfig(themeKey: any, props: any, opts: any) {
+export function useStyleConfig(themeKey: any, props: any = {}, opts: any = {}) {
```
Comment (TimKolberger) [inline packages/system/src/use-style-config.ts:26]: Would the type `Record<string, any>` for `props` and `opts` help with this?

Comment (with-heart) [reply packages/system/src/use-style-config.ts:26]: I'm not sure it makes a difference. The `any` types are devoured by the overrides, and it seems like `Record<string, any>` and `any` both work fine with the defaults specified.

Comment (TimKolberger) [reply packages/system/src/use-style-config.ts:26]: Oh, I missed the overrides! 👍

**Review by TimKolberger — APPROVED** [review]
