### PR TITLE
fix(popover): arrowshadowcolor not working

### LINKED ISSUE #4127: Popover arrowShadowColor is not working
# 🐛 Bug report

Hello,
I am trying to change the arrow shadow in Popover, as I follow the [doc](https://chakra-ui.com/docs/overlay/popover) . The Popover takes `arrowShadowColor` as a prop, but it never gets apply to the component arrow. 

## 💥 Steps to reproduce

1. Go to 'https://codesandbox.io/s/chakra-ui-header-forked-l37o6?file=/src/index.js'
2. Click on 'Trigger' to open the Popover
3. I passed the color `red.900` to the prop `arrowShadowColor`, but it does not reflect on the component
image

## 💻 Link to reproduction
https://codesandbox.io/s/chakra-ui-header-forked-l37o6?file=/src/index.js

## 🧐 Expected behavior

The arrow shadow should reflect the value being passed as prop

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |   1.6.1         |
| Browser          |    Chrome        |
| Operating System |  Version 91.0.4472.77 (Official Build) (x86_64)  |

### PR DESCRIPTION
**Pull request by anubra266**
Closes #4127

### CODE REVIEW

File: packages/popover/src/use-popover.ts [hunk 1]
```diff
@@ -197,6 +197,9 @@ export function usePopover(props: UsePopoverProps = {}) {
         style: {
           ...props.style,
           transformOrigin: popperCSSVars.transformOrigin.varRef,
+          [popperCSSVars.arrowSize.var]: arrowSize ? px(arrowSize) : undefined,
+          [popperCSSVars.arrowShadowColor.var]: arrowShadowColor,
+          visibility: isOpen ? "visible" : "hidden",
```
Comment (segunadebayo) [inline packages/popover/src/use-popover.ts:202]: Any reason to move the `visibility` style?

Comment (anubra266) [reply packages/popover/src/use-popover.ts:202]: No...that's a mistake. Changing now.
