### PR TITLE
fix(accordion):  introduce `styles.root` for `Accordion`

### LINKED ISSUE #5593: Accordion items not stylable as a theme part (or at least not how you'd expect it to)
### Description

When I specify styles for the accordion's `item` parts key.

### Link to Reproduction

https://codesandbox.io/s/dazzling-lichterman-95c36v?file=/src/index.js

### Steps to reproduce

1. Open the code sandbox
2. Notice how the theme.components.Accordion.baseStyle.item styles are ignored
3. Notice how the theme.components.Accordion.baseStyle.container styles are placed on the AccordionItem

I'm implementing my own design for accordions through specifying my own theme.

When I specify changes for the item key, they're just ignored.

When I look at the code, it looks like the `styles.container` styles are spread onto the AccordionItem, not the Accordion.

This should probably be addressed, and doing so would be pretty straight forward, but it would break existing implementations. 

Should we change it so that `container` styles are added to the `Accordion` component, and `item` styles to the `AccordionItem` component, or should we save this change for a future major release?

### Chakra UI Version

1.6.4

### Browser

_No response_

### Operating System

- [X] macOS
- [X] Windows
- [X] Linux

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by takethefake**
closes #5593 

## 📝 Description

Updated style config for `Accordion`

This change introduces `styles.root` for `Accordion`

## 💣 Is this a breaking change (Yes/No):

No

### CODE REVIEW

**Comment by TimKolberger** [comment]
Thank you @takethefake for your time creating this PR!

I think there might be a way to fix this issue without a breaking change.

What do you think about adding a new part `root` to the [accordionAnatomy](https://github.com/chakra-ui/chakra-ui/blob/main/packages/anatomy/src/index.ts) and using it instead of moving `container` from the AccordionItem to the Accordion?

With v2 in mind we could reuse `root` for every MultipartComponent to make it a pattern. Why `root` and not `container`? Some components might have a container, like Tab or Accordion, but when thinking about a button it is hard to define where the container is. `root` is IMO easy to identify as the style root, which is always the top most DOM element of a component.

Kindly let me know your thoughts!

**Comment by takethefake** [comment]
Hej @TimKolberger 

this sounds like a good approach to provide new functionality. We definitely need to make sure in v2 that we unify the usage of `root` / `container` to be clearly.

Adjusted the pr accordingly.

File: packages/anatomy/src/index.ts [hunk 1]
```diff
@@ -2,13 +2,14 @@ import { anatomy } from "@chakra-ui/theme-tools"
...
- * - Item: the accordion item contains the button and panel
+ * - Root: the root container of the accordion
+ * - Container: the accordion item contains the button and panel
  * - Button: the button is the trigger for the panel
  * - Panel: the panel is the content of the accordion item
  * - Icon: the expanded/collapsed icon
  */
 export const accordionAnatomy = anatomy("accordion")
-  .parts("container", "item", "button", "panel")
+  .parts("root", "container", "button", "panel")
```
Comment (TimKolberger) [inline packages/anatomy/src/index.ts:12]: I think the `item` is missing in the list.

File: packages/accordion/src/accordion.tsx [hunk 2]
```diff
@@ -58,6 +58,10 @@ export const Accordion = forwardRef<AccordionProps, "div">(
       [context, reduceMotion],
     )
 
+    const rootStyles: SystemStyleObject = {
```
Comment (TimKolberger) [inline packages/accordion/src/accordion.tsx:61]: Could this be inlined to the __css prop?

**Review by TimKolberger — CHANGES_REQUESTED** [review]
Thank you for updating the PR so fast, I added a few comments.
Then it looks good to go 🚀

File: packages/accordion/src/accordion.tsx (hunk 2 above)
Comment (takethefake) [reply packages/accordion/src/accordion.tsx:61]: sure!

File: packages/anatomy/src/index.ts (hunk 1 above)
Comment (takethefake) [reply packages/anatomy/src/index.ts:12]: we don't use `item` in accordion. I think this is why those styles are kind of mixed up.

Comment (TimKolberger) [reply packages/anatomy/src/index.ts:12]: Ah got it. Thanks 👍

**Review by TimKolberger — APPROVED** [review]

File: packages/accordion/src/accordion.tsx (hunk 2 above)
Comment (TimKolberger) [reply packages/accordion/src/accordion.tsx:61]: Awesome 😊

Comment (takethefake) [reply packages/accordion/src/accordion.tsx]: @TimKolberger adjusted it
