### PR TITLE
fix: buttons zIndex in linkbox with usage of link overlay

### LINKED ISSUE #5673: LinkOverlay breaks IconButton/Button within LinkBox
### Description

The latest release (1.8.6) introduced a new bug.

When using a LinkBox + LinkOverlay, any IconButton within the LinkBox becomes unresponsive.

### Link to Reproduction

https://codesandbox.io/s/bold-leaf-rhjbxj?file=/src/index.tsx

### Steps to reproduce

Hover over the + icon, you can see that there is no animation, and clicking it doesn't log anything to the console.

### Chakra UI Version

1.8.6

### Browser

Safari 

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

Removing the LinkOverlay component seems to fix it, but obviously that makes the whole link box feature not very useful.

### PR DESCRIPTION
**Pull request by m4x3d**
Closes #5673 

## 📝 Description

This fixes a problem that buttons are no longer clickable within a `LinkBox` with a `LinkOverlay`  because of the zIndex. This is a result of the changes of https://github.com/chakra-ui/chakra-ui/pull/5632.

## ⛳️ Current behavior (updates)

Buttons are not clickable if they are within a `LinkBox` with a `LinkOverlay`, see e.g. the CSB from the issue: https://codesandbox.io/s/bold-leaf-rhjbxj?file=/src/index.tsx

## 🚀 New behavior

Buttons are clickable again, this should represent the fix: https://codesandbox.io/s/stoic-glitter-9em593

## 💣 Is this a breaking change (Yes/No):

No

## 📝 Additional Information

It worked also with `zIndex: 1` on Firefox 97.0 and Chromium 99.0.4844.51 but it feels wrong so that I set it to 2 to avoid unexpected behavior on other browsers/versions.

### CODE REVIEW

File: packages/layout/src/link-box.tsx [hunk 1]
```diff
@@ -54,10 +54,10 @@ export const LinkBox = forwardRef<LinkBoxProps, "div">((props, ref) => {
       {...rest}
       className={cx("chakra-linkbox", className)}
       __css={{
-        /* Elevate the links and abbreviations up */
-        "a[href]:not(.chakra-linkbox__overlay), abbr[title]": {
+        /* Elevate the links, abbreviations and buttons up */
+        "a[href]:not(.chakra-linkbox__overlay), abbr[title], button": {
           position: "relative",
-          zIndex: 1,
+          zIndex: 2,
```
Comment (TimKolberger) [inline packages/layout/src/link-box.tsx:60]: Did you encounter any issues with `zIndex: 1`?
I think `zIndex: 1` should suffice, because the `::before` element will always be _before_ any other child DOM element. Trailing DOM elements with `zIndex: 1` should be on top.

Comment (m4x3d) [reply packages/layout/src/link-box.tsx]: Aaah, that makes sense. I did not figured out why `zIndex: 1` worked as expected so I set it to 2 to avoid any other unexpected behavior with other browsers/browser version.

I force-pushed it.
