### PR TITLE
Fix/select icon rtl

### LINKED ISSUE #3755: Select icon should be at the inline-end for RTL
# 🐛 Bug report

The icon for `Select` is always on the right, regardless of LTR or RTL.

## 💥 Steps to reproduce

1. Go to the sandbox
2. Check the icon position

## 💻 Link to reproduction

CodeSandbox reproduction: https://codesandbox.io/s/chakra-ui-select-rtl-icon-1kwbx

## 🧐 Expected behavior

The icon should be at the end (on the left for RTL, right for LTR)

image

## 🧭 Possible Solution

It should be placed at the inline-end, instead of right. 

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |      1.4.2      |
| Browser          |      Chrome      |
| Operating System |      Windows 10      |

### PR DESCRIPTION
**Pull request by estheragbaje**
Closes #3755

## 📝 Description

Updated RTL support such that we use `inlineStart` instead of `left` and `inlineEnd` instead of `right` for Select Component theme.

## ⛳️ Current behavior (updates)

On RTL, the select icon was still showing up on the right instead of flipping to the left.

## 🚀 New behavior

On RTL, the select icon shows on the left. 

## 💣 Is this a breaking change (Yes/No):

No

### CODE REVIEW

File: packages/theme/src/components/select.ts [hunk 1]
```diff
@@ -19,7 +19,7 @@ function baseStyleField(props: Record<string, any>) {
 const baseStyleIcon = {
   width: "1.5rem",
   height: "100%",
-  right: "0.5rem",
+  insetEnd: "0.5rem",
```
Comment (manzoorwanijk) [inline packages/theme/src/components/select.ts:22]: Shouldn't this be `insetInlineEnd`? 🤔
