### PR TITLE
fix(popper): arrow box shadow

### LINKED ISSUE #7005: Multipart component theming doesn't work for Popover arrow
### Description

Bumping a previous bug report that was erroneously marked Closed without being addressed.

[Link to @noobinthisgame's original report](https://github.com/chakra-ui/chakra-ui/issues/5821)

### Link to Reproduction

https://codesandbox.io/s/cool-newton-xw6kie?file=/src/App.js

### Steps to reproduce

1. Go to Codesandbox
2. See the theme with the arrow part.
3. It has no effect

### Chakra UI Version

2.4.1

### Browser

Google Chrome 93, Mozilla Firefox 106.0.5 

### Operating System

- [X] macOS
- [X] Windows
- [ ] Linux

### Additional Information

Also maybe worth noting that the Popover Theming page is not populated:

https://chakra-ui.com/docs/components/popover/theming

### PR DESCRIPTION
**Pull request by anubra266**
Closes #7005

- Allows overriding popper arrow `background` and `boxShadow` with css variables
- Allows setting popover arrow `boxShadow` with the `shadow` prop

### CODE REVIEW

File: packages/components/popover/src/popover-arrow.tsx [hunk 1]
```diff
@@ -1,14 +1,15 @@
-import { chakra, HTMLChakraProps } from "@chakra-ui/system"
+import { chakra, HTMLChakraProps, SystemStyleObject } from "@chakra-ui/system"
```
Comment (anubra266) [inline packages/components/popover/src/popover-arrow.tsx:1]:
```suggestion
import { chakra, HTMLChakraProps } from "@chakra-ui/system"
```
