### PR TITLE
fix: breakpoint tokens missing

### LINKED ISSUE #5045: useToken 'breakpoints' not returning values
### Description

When I use 'breakpoints' in useToken, I expect it to return a width value

### Link to Reproduction

https://codesandbox.io/s/flamboyant-poincare-19xm1

### Steps to reproduce

```
const [sm, lg] = useToken("breakpoints", ["sm", "lg"]);
const [red500] = useToken("colors", ["red.500"]);

console.log({ sm, lg, red500 });
```

### Chakra UI Version

1.6.12

### Browser

Chrome Version 95.0.4638.69 (Official Build) (x86_64)

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

Looks like this broke in this release  #4867 (system@1.7.5), because its still working in #4799 (system@1.7.4)

Looking a little deeper, it looks like its caused by [this change](https://github.com/chakra-ui/chakra-ui/pull/4842/commits/ed79a9cfb35fec67bfe95bbc2a04a11d0d00fbfe?authenticity_token=pFuI7Hv6vrORYKZl6%2B%2F5X6aG0fKZ4WgOLS%2ButWQB%2BApTQfYfEjR1C0ShoPQwmDMAbezF2DlGnP9plbMI6r4ZOw%3D%3D&file-filters%5B%5D=.ts#diff-ef4dabe3d75896dfa76d3b8ec8df948184ad08f711e41715e65253a1b294ae4fR29) because `breakpoints` is not a part of `__cssMap`

### PR DESCRIPTION
**Pull request by primos63**
Closes #5045 

## 📝 Description

> Restore ability to get breakpoint token value(s) via useToken

## ⛳️ Current behavior (updates)

>  A request for breakpoint token values, useToken("breakpoints", "sm"), would always return the default value as useToken did not include breakpoints in the lookup.

## 🚀 New behavior

> useToken has been modified to account for breakpoint token requests.

### CODE REVIEW

File: packages/system/src/hooks.ts [hunk 1]
```diff
@@ -19,14 +19,33 @@ export function useChakra<T extends Dict = Dict>() {
...
   fallbackValue: any,
 ) => {
   if (tokenValue == null) return tokenValue
-  const getValue = (val: T) => theme.__cssMap?.[val]?.value
+  const scale = tokenValue.toString().split(".")[0]
+  const getValue =
+    scale !== "breakpoints"
+      ? (val: T) => theme.__cssMap?.[val]?.value
+      : (val: T) => theme.__breakpoints?.[val]?.value
+  // const getValue = (val: T) => theme.__cssMap?.[val]?.value
```
Comment (segunadebayo) [inline packages/system/src/hooks.ts:48]: The code here feels a bit more complex than needed. Maybe we can collaborate on this to find opportunities to simplify this.

**Comment by segunadebayo** [comment]
@primos63, I've gone ahead to clean up the code as we discussed the other day.

Take a look at the let me know if it's good to go.

**Comment by primos63** [comment]
@segunadebayo All good! Thanks. Much appreciated!
