### PR TITLE
fix(css-vars): escape symbols in css var

### LINKED ISSUE #5424: Color name token with symbols
### Description

Color names with $ no longer work (`$red`)

### Link to Reproduction

https://codesandbox.io/s/confident-kalam-27b3m

### Steps to reproduce

Some where between `1.2.1` and `latest` color names can no longer start a symbol. Anyone know what change might have caused it and why? I'm happy to work on a fix.

### Chakra UI Version

latest

### Browser

Firefox, Chrome, Safari

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by yukukotani**
Closes #5424

## 📝 Description

> Add a brief description

Tokens that include symbols in the name are broken. This PR makes it works by escaping symbols.

## ⛳️ Current behavior (updates)

> Please describe the current behavior that you are modifying

https://codesandbox.io/s/confident-kalam-27b3m

With the following code, the background color is still transparent in spite of `bg` property being `$red`. The CSS variable will be `--chakra-colors-$red` that invalid.

```tsx
function App() {
  return <Heading bg="$red">Welcome to Chakra + TS</Heading>;
}

const rootElement = document.getElementById("root");
render(
  <ChakraProvider theme={extendTheme({ colors: { $red: "#880000" } })}>
    <App />
  </ChakraProvider>,
  rootElement
);
```

## 🚀 New behavior

> Please describe the behavior or changes this PR adds

https://codesandbox.io/s/competent-bush-hm9pmu

The background color is applied correctly. The CSS variable will be escaped to `--chakra-colors-\$red`.

## 💣 Is this a breaking change (Yes/No):

No

### CODE REVIEW

File: packages/styled-system/src/create-theme-vars/css-var.ts [hunk 1]
```diff
@@ -4,21 +4,30 @@ function replaceWhiteSpace(value: string, replaceValue = "-") {
...
+
+  return escapeSymbol(escapeDot(valueStr))
+}
+
+function escapeDot(value: string) {
+  if (value.includes("\\.")) return value
   const isDecimal = !Number.isInteger(parseFloat(value.toString()))
-  return isDecimal ? valueStr.replace(".", `\\.`) : value
+  return isDecimal ? value.replace(".", `\\.`) : value
+}
```
Comment (yukukotani) [inline packages/styled-system/src/create-theme-vars/css-var.ts:15]: I really don't understand this logic, so have remained to be same.

File: packages/styled-system/src/create-theme-vars/css-var.ts [hunk 2]
```diff
@@ -4,21 +4,30 @@ function replaceWhiteSpace(value: string, replaceValue = "-") {
...
 
 export function toVarReference(name: string, fallback?: string) {
-  return `var(${escape(name)}${fallback ? `, ${fallback}` : ""})`
+  return `var(${name}${fallback ? `, ${fallback}` : ""})`
 }
 
 export function toVarDefinition(value: string, prefix = "") {
-  return `--${addPrefix(value, prefix)}`
+  return escape(`--${addPrefix(value, prefix)}`)
 }
```
Comment (yukukotani) [inline packages/styled-system/src/create-theme-vars/css-var.ts:31]: Avoids calling `escape` multiple times.

File: packages/styled-system/src/create-theme-vars/css-var.ts [hunk 3]
```diff
@@ -4,21 +4,30 @@ function replaceWhiteSpace(value: string, replaceValue = "-") {
...
+function escapeDot(value: string) {
+  if (value.includes("\\.")) return value
   const isDecimal = !Number.isInteger(parseFloat(value.toString()))
-  return isDecimal ? valueStr.replace(".", `\\.`) : value
+  return isDecimal ? value.replace(".", `\\.`) : value
+}
+
+function escapeSymbol(value: string) {
+  return value.replace(/[!-,/:-@[-^`{-~]/g, "\\$&")
 }
```
Comment (yukukotani) [inline packages/styled-system/src/create-theme-vars/css-var.ts:19]: This is the main change of this PR
