### PR TITLE
fix: localstorage error in iframe or incognito

### LINKED ISSUE #3202: Using Chakra UI for a page that is rendered inside an iframe crashes the site
# 🐛 Bug report

> Using Chakra UI for a page that is rendered inside an iframe crashes the site since Chakra UI is not able to access localstorage which is required for Color Mode

## 💥 Steps to reproduce

1. Setup a simple NextJS project and add Chakra UI to it
2. Try to embed a page of this project inside an iframe

## 🧐 Expected behavior

> Page does not crash

## 🧭 Possible Solution

> If the page is inside an iframe, a method to tell Chakra to not try to access localstorage

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |  1.0.4          |
| Browser          | Chromium           |
| Operating System | Linux           |

## 📝 Additional information
Here's the stack trace
```
SecurityError: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.

Call Stack
Object.get
./node_modules/@chakra-ui/color-mode/dist/esm/storage-manager.js (13:0)
eval
./node_modules/@chakra-ui/color-mode/dist/esm/color-mode-provider.js (61:77)
invokePassiveEffectCreate
./node_modules/react-dom/cjs/react-dom.development.js (23487:0)
HTMLUnknownElement.callCallback
./node_modules/react-dom/cjs/react-dom.development.js (3945:0)
Object.invokeGuardedCallbackDev
./node_modules/react-dom/cjs/react-dom.development.js (3994:0)
invokeGuardedCallback
./node_modules/react-dom/cjs/react-dom.development.js (4056:0)
flushPassiveEffectsImpl
./node_modules/react-dom/cjs/react-dom.development.js (23574:0)
unstable_runWithPriority
./node_modules/scheduler/cjs/scheduler.development.js (646:0)
runWithPriority$1
./node_modules/react-dom/cjs/react-dom.development.js (11276:0)
flushPassiveEffects
./node_modules/react-dom/cjs/react-dom.development.js (23447:0)
eval
./node_modules/react-dom/cjs/react-dom.development.js (23324:0)
workLoop
./node_modules/scheduler/cjs/scheduler.development.js (590:0)
flushWork
.node_modules/scheduler/cjs/scheduler.development.js (545:0)
MessagePort.performWorkUntilDeadline
./node_modules/scheduler/cjs/scheduler.development.js (157:0)
```

### PR DESCRIPTION
**Pull request by segunadebayo**
Closes #3202 #3252

## 📝 Description

Reading from localStorage directly can fail due to several reasons. When rendered in an iframe or incognition, it could throw a SecurityError, Uncaught DOMException, TypeError, etc. To handle this, I wrapped the calls to localStorage in a try-catch block.

## ⛳️ Current behavior (updates)

Throws when rendered in an iframe or codesandbox incognito

### CODE REVIEW

File: packages/color-mode/src/storage-manager.ts [hunk 1]
```diff
@@ -14,17 +17,25 @@ export interface StorageManager {
...
-
-    const maybeValue = window.localStorage.getItem(storageKey) as ColorMode
-
-    return maybeValue ?? init
   },
   set(value) {
-    if (hasLocalStorage) {
+    if (!hasSupport()) return
+    try {
       window.localStorage.setItem(storageKey, value)
```
Comment (segunadebayo) [inline packages/color-mode/src/storage-manager.ts:34]:
```suggestion
     localStorage.setItem(storageKey, value)
```
