### PR TITLE
fix: resolve native input size prop conflict with input theme props

### LINKED ISSUE #5489: Theming prop `size` conflicts with input prop `size`
### Description

When I want to set the DOM attribute `size={3}` of an `<input>` element, I am unable to do it with `<Input>` since `size` is interpreted as a theme prop, and not a native attribute.

### Link to Reproduction

https://codesandbox.io/s/jovial-mendeleev-upylk?file=/src/index.js

### Steps to reproduce

See above CodeSandbox

### Chakra UI Version

1.6.3

### Browser

_No response_

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by noobinthisgame**
Closes #5489 

## 📝 Description

Add htmlSize prop to enable the usage of the native size prop and to resolve the conflict with the input theme prop size.

## ⛳️ Current behavior (updates)

The native input size prop can't be used because it gets overriden by the input theme prop size.

## 🚀 New behavior

There is a new htmlSize prop to pass the native size prop to an input.

## 💣 Is this a breaking change (Yes/No):

No

## 📝 Additional Information

Added Storybook story to test the behaviour with the native size prop

### CODE REVIEW

File: packages/input/src/input.tsx [hunk 1]
```diff
@@ -6,11 +6,28 @@ import {
...
+
+interface NativeInputProps extends PropsOf<"input">, NativeInputOptions {}
+
+const NativeInput = React.forwardRef(
+  (props: NativeInputProps, ref: React.Ref<any>) => {
+    const { htmlSize, ...rest } = props
+    return <input size={htmlSize} ref={ref} {...rest} />
+  },
+)
+
```
Comment (TimKolberger) [inline packages/input/src/input.tsx:29]: I think we can solve this without introducing an additional component. 
The intended behavior can be achieved by using the chakra factory function `<chakra.input />`

File: packages/input/src/input.tsx [hunk 2]
```diff
@@ -47,15 +64,23 @@ export interface InputProps
...
+  const { width, ...fieldStyles } = styles.field
+  const cssStyles = htmlSize ? { ...fieldStyles } : { ...styles.field }
+
   return (
     <chakra.input
+      as={NativeInput}
+      htmlSize={htmlSize}
       {...input}
-      __css={styles.field}
+      __css={{ ...cssStyles }}
```
Comment (TimKolberger) [inline packages/input/src/input.tsx:83]: We can safely omit the spread operator here: 

```suggestion
      __css={cssStyles}
```

File: packages/input/src/input.tsx [hunk 3]
```diff
@@ -47,15 +64,23 @@ export interface InputProps
...
   const input = useFormControl<HTMLInputElement>(ownProps)
   const _className = cx("chakra-input", props.className)
 
+  // This is used to remove the default width=100% when size is set, which otherwise conflicts
+  const { width, ...fieldStyles } = styles.field
+  const cssStyles = htmlSize ? { ...fieldStyles } : { ...styles.field }
+
   return (
     <chakra.input
+      as={NativeInput}
```
Comment (TimKolberger) [inline packages/input/src/input.tsx:80]: I think we can omit this, because

```tsx
<chakra.input size="2" />
// renders
<input size="2" />
```

```suggestion
```

**Review by TimKolberger — CHANGES_REQUESTED** [review]
Thank you for this PR @noobinthisgame 💖 
I added my thoughts as comments. 
Feel free to reach out if you have further questions!

File: packages/input/src/input.tsx (hunk 1 above)
Comment (noobinthisgame) [reply packages/input/src/input.tsx:29]: Indeed that works. Definitely cleaner.

File: packages/input/src/input.tsx (hunk 2 above)
Comment (noobinthisgame) [reply packages/input/src/input.tsx:83]: Right that's a relict from testing. Remove it.

File: packages/input/src/input.tsx [hunk 4]
```diff
@@ -47,15 +51,22 @@ export interface InputProps
...
+  const { htmlSize, ...rest } = props
+
+  const styles = useMultiStyleConfig("Input", rest)
+  const ownProps = omitThemingProps(rest)
   const input = useFormControl<HTMLInputElement>(ownProps)
   const _className = cx("chakra-input", props.className)
 
+  // This is used to remove the default width=100% when size is set, which otherwise conflicts
+  const { width, ...fieldStyles } = styles.field
+  const cssStyles = htmlSize ? { ...fieldStyles } : { ...styles.field }
```
Comment (TimKolberger) [inline packages/input/src/input.tsx:63]: I'm not quite sure we want to predict the user's goal here.

From the perspective of the using side I find it much easier to understand whats happening when the width is explicitly set like `<Input htmlSize="10" width="auto" />`.

Otherwise we would need to filter the props `width` and `w` respectively.

What do you think about that?

File: packages/input/tests/input.test.tsx [hunk 5]
```diff
@@ -45,3 +45,9 @@ test("Readonly input renders correctly", () => {
 
   expect(screen.getByRole("textbox")).toHaveAttribute("aria-readonly", "true")
 })
+
+test("Input with native size renders correctly", () => {
+  render(<Input htmlSize={4} />)
+
+  expect(screen.getByRole("textbox")).toHaveAttribute("size", "4")
+})
```
Comment (TimKolberger) [inline packages/input/tests/input.test.tsx:53]: 🦄 💖

File: packages/input/src/input.tsx (hunk 4 above)
Comment (noobinthisgame) [reply packages/input/src/input.tsx:63]: I think that building around the default theme width is overcomplicating the component. I'd be happy to remove it to make the component more transparent in usage and less funky. Just didn't wanted to make too many changes everywhere.
Removing the default theme width might result in a breaking change tho, as we don't know how many people rely on this, as it's a default. 😕

Comment (TimKolberger) [reply packages/input/src/input.tsx:63]: > I'd be happy to remove it to make the component more transparent in usage and less funky.

Sounds great! 

> Removing the default theme width might result in a breaking change 

Yes, this would be a breaking change IMO and not necessary to introduce a new html prop.

Comment (noobinthisgame) [reply packages/input/src/input.tsx:63]: Actually I don't get why we wouldn't need the new htmlProp ? We still have the issue that theme size and native size conflict here ?

Comment (TimKolberger) [reply packages/input/src/input.tsx:63]: I think I did not express my self clearly 😅 
It is great to add support for the html `size` attribute! But I think this does not mean to introduce a breaking change to the theme. 
If a user wants to use `htmlSize` I think it is much cleaner to let them use `<Input htmlSize="10" width="auto" />` instead of internally omitting the styleProp `width`.

Comment (noobinthisgame) [reply packages/input/src/input.tsx:63]: Ahhh I right I got it. Docs thing then for the usage of the htmlSize and to override default width with auto. Gotcha. Will make those changes and open a PR in docs aswell 😄

**Review by TimKolberger — APPROVED** [review]
lgtm 🚀

**Comment by noobinthisgame** [comment]
@TimKolberger Here is the according docs https://github.com/chakra-ui/chakra-ui-docs/pull/277 
Let me know if thats enough 😊

**Comment by noobinthisgame** [comment]
@nikolovlazar Would it make sense to have labels for PRs like this one that should only be merged when a feature is actually released in the main repo ?
