### PR TITLE
fix(transform-functions): bgImage url bool condition

### LINKED ISSUE #4043: <Progress isIndeterminate /> is not working
# 🐛 Bug report
`<Progress isInderterminate/>` is not working (even on the documentation page https://chakra-ui.com/docs/feedback/progress#animated-progress)

## 💥 Steps to reproduce

1. `<Progress isIndeterminate /> `
2. nothing is shown 

## 💻 Link to reproduction

Documentation link https://chakra-ui.com/docs/feedback/progress#animated-progress

## 🧐 Expected behavior

Should show progress flashing 

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |       ^1.6.2     |
| Browser          |     Firefox       |
| Operating System |     MacOS       |

### PR DESCRIPTION
**Pull request by mcha-dev**
Closes #4043 🤞

## 📝 Description

Please check issue description & comments

## ⛳️ Current behavior (updates)

<Progress /> with isIndeterminate not working 

## 🚀 New behavior

Fix 🤞

## 💣 Is this a breaking change (Yes/No):

I hope not.

### CODE REVIEW

File: packages/styled-system/src/utils/transform-functions.ts [hunk 1]
```diff
@@ -82,3 +84,7 @@ export const transformFunctions = {
     return result
   },
 }
+
+const isCSSFunction = (value: unknown) => {
```
Comment (mcha-dev) [inline packages/styled-system/src/utils/transform-functions.ts:88]: Nice! I was thinking of a more complicated approach. i.e. regexing against possible bgImage gradients

linear-gradient
repeating-linear-gradient
radial-gradient
repeating-radial-gradient
conic-gradient
repeating-conic-gradient
