### PR TITLE
fix(icon): expose icon to theme

### LINKED ISSUE #6939: Icons have no way of touching defaultProps
### Description

When using the Icon component it does not seem to have any part in the theme object. This means we cannot alter the icon default props. Namely the height set to 1em. This should be auto.

Not every icon is perfectly square. And 1em on the height can chop it a bit. 

The width can be 1em but height should be auto.

### Link to Reproduction

no link

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Chakra UI Version

2.3.7

### Browser

_No response_

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by anubra266**
Closes #6939
Expose Icon component to theme

### CODE REVIEW

File: packages/components/icon/src/icon.tsx [hunk 1]
```diff
@@ -27,7 +28,7 @@ const fallbackIcon = {
 
 export interface IconProps
   extends Omit<React.SVGAttributes<SVGElement>, keyof ChakraProps>,
-    ChakraProps {}
+    Omit<ChakraProps, "orientation"> {}
```
Comment (segunadebayo) [inline packages/components/icon/src/icon.tsx:31]: Why the need for this? Just curious

Comment (anubra266) [reply packages/components/icon/src/icon.tsx:31]: @segunadebayo it clashes with the typings for `styleConfig` decided to omit it since Icon doesn't need it.

File: .changeset/short-deers-beg.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+"@chakra-ui/icon": patch
+---
+
+Hook Icon component to theme
```
Comment (segunadebayo) [inline .changeset/short-deers-beg.md:5]:
```suggestion
Add support for styling the Icon component from the theme object.
```
