### PR TITLE
fix(input-group): input group theming passing undefined props

### LINKED ISSUE #5103: InputGroup overrides Input variant
### Description

I created a styled component with Chakra ForwardRef, which had variant="flushed" by default. When i was using this component, it had variant="outline" set. I finally discovered this was because of InputGroup.

### Link to Reproduction

https://codesandbox.io/s/chakra-ui-forked-t9q2s

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Chakra UI Version

1.6.10

### Browser

Google chrome 93

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by anubra266**
Closes #5103

Input group passes undefined `size` and `variant` which overrides the ones defined by default in a custom `Input` component.

### CODE REVIEW

File: packages/input/src/input-group.tsx [hunk 1]
```diff
@@ -50,11 +50,16 @@ export const InputGroup = forwardRef<InputGroupProps, "div">((props, ref) => {
...
+    const themingSize = child.props?.size || props.size
+    const themingVariant = child.props?.variant || props.variant
     const theming = {
-      size: child.props?.size || props.size,
-      variant: child.props?.variant || props.variant,
+      ...(themingSize && { size: themingSize }),
+      ...(themingVariant && { variant: themingVariant }),
     }
 
+    console.log(child.props)
```
Comment (segunadebayo) [inline packages/input/src/input-group.tsx:61]:
```suggestion
```
