### PR TITLE
Fix hydration issues

### LINKED ISSUE #5842: ChakraProvider breaks Suspense in Next.js projects, even without suspended components
### Description

When you add ChakraProvider to _app.tsx, any usage of Suspense breaks the app.

### Link to Reproduction

https://codesandbox.io/s/nice-wood-50d2lj?file=/pages/index.tsx

### Steps to reproduce

1) Create a vanilla Next.js app
2) Add a Suspense component with `<p>Hello world</p>` as children into pages/index.tsx
3) Verify it works fine (should)
4) Add @chakra-ui/react and `<ChakraProvider>` into _app.tsx
5) Reload the page - emits the following error:

`Error: This Suspense boundary received an update before it finished hydrating. This caused the boundary to switch to client rendering. The usual way to fix this is to wrap the original update in startTransition.`

### Chakra UI Version

1.8.8 and @next

### Browser

_No response_

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

_No response_

### LINKED ISSUE #6129: ChakraProvider breaks Suspense when reloading in Next.js project
### Description

When I reloaded the screen I used with react 18 suspense and Next.js, I expected to display correctly happen but instead an error was displayed.

### Link to Reproduction

https://codesandbox.io/s/stoic-violet-b8beh4?file=/pages/index.tsx

### Steps to reproduce

1. Create Next.js App
2. Add a Suspense component into pages/index.tsx
3. Verify it works fine (should)
4. Add @chakra-ui/react and <ChakraProvider> into _app.tsx
5. Reload the page - emits the following error:

```
Unhandled Runtime Error
Error: Hydration failed because the initial UI does not match what was rendered on the server.
```

### Chakra UI Version

2.1.2

### Browser

Firefox, Chrome, Safari

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

This issue seemed to have solved the problem, but it still seems to be occurring.
Please check.

https://github.com/chakra-ui/chakra-ui/issues/5842

### PR DESCRIPTION
**Pull request by itkrt2y**
Closes #6129
Closes #5842

## 📝 Description

Additional implementation of #6171.

Fix hydration issues of  `EnvironmentProvider` and `ColorModeProvider`

## ⛳️ Current behavior (updates)

In SSR with Suspense, `EnvironmentProvider` and `ColorModeProvider` do not work because of hydration issue.

## 🚀 New behavior

Works as expected

## 💣 Is this a breaking change (Yes/No):

No

### CODE REVIEW

File: packages/env/src/env.tsx [hunk 1]
```diff
@@ -57,7 +58,9 @@ export function EnvironmentProvider(props: EnvironmentProviderProps) {
       {mounted && (
         <span
           ref={(el) => {
-            if (el) setNode(el)
+            startTransition(() => {
```
Comment (itkrt2y) [inline packages/env/src/env.tsx:61]: I thought this `startTransition` was unnecessary in the previous [PR](https://github.com/chakra-ui/chakra-ui/pull/6171#discussion_r903752912), but I reverted it because `EnvironmentProvider` needed `startTransition`.
