### PR TITLE
fix(button): #3859 fix button type as undefined

### LINKED ISSUE #3859: PopoverTrigger child Button type is undefined
# 🐛 Bug report

I use PopoverTrigger in form, but PopoverTrigger's child Button type is undefined
when click Trigger, form submit always trigger

## 💻 Link to reproduction

CodeSandbox reproduction: https://codesandbox.io/s/hopeful-shamir-fcd4q?file=/src/App.tsx

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |  1.5.2          |
| Browser          |    Chrome 90        |
| Operating System |    macOS 11.2.3        |

### PR DESCRIPTION
**Pull request by antoniel**
Closes #3859 , #3871 

## 📝 Description

Fixes issue where button wasn't receiving type prop on first mount

## ⛳️ Current behavior (updates)

Button does not receive type="button", even when passed in as a prop.

## 🚀 New behavior

If is a button, so doesn't have a as props should receive `type={type}` where default type is a button

## 💣 Is this a breaking change (Yes/No):

No

### CODE REVIEW

File: packages/button/src/button.tsx [hunk 1]
```diff
@@ -118,17 +117,12 @@ export const Button = forwardRef<ButtonProps, "button">((props, ref) => {
     ...(!!group && { _focus }),
   }
 
-  const [isButton, setIsButton] = React.useState(!as)
-  const refCallback = React.useCallback((node: HTMLElement | null) => {
-    if (node?.tagName !== "BUTTON") {
-      setIsButton(false)
-    }
-  }, [])
+  const isButton = Boolean(!as)
```
Comment (TimKolberger) [inline packages/button/src/button.tsx:120]: This solution is a bit too simple. The `as` prop could be a React Component which renders a button.
Checking the `node.tagName` is necessary.

The optional chaining operator `node?.tagName` returns `undefined | string`. If it is `undefined` we do not want to take any action, because we cannot be sure if it is not a button.

The previous logic with this change should to the trick:

```js
if (node && node.tagName !== "BUTTON") {
  setIsButton(false)
}
```

**Review by TimKolberger — CHANGES_REQUESTED** [review]
Thanks for creating a PR for this @antoniel ✨

File: packages/button/src/button.tsx (hunk 1 above)
Comment (antoniel) [reply packages/button/src/button.tsx:120]: Can we use OR operator to check the case `as="button"`? On the pervious logic, if `as` exists `isButton = false` and there's no trigger to set it to true.

Something like: 
```tsx
const isButton = Boolean(!as) || Boolean(as === "button")
```

Comment (TimKolberger) [reply packages/button/src/button.tsx:120]: Good catch, the initialState would be `false` if an `as` prop would be provided.

```js
const [isButton, setIsButton] = React.useState(!as || as === 'button')

// ...

if (node && node.tagName !== "BUTTON") { 
  setIsButton(false) 
}
```

What do you think?


I am getting curious: @segunadebayo do you have any insights why the `tagName` check was introduced?

Comment (antoniel) [reply packages/button/src/button.tsx]: I've implemented and extend test cases, i'm also curious about tagName check seems unnecessary to me

**Comment by aboveyunhai** [comment]
Sorry for @segunadebayo,  but the problem related to this one need to be address as quickly as possible. 
Since `type` is not correctly passed into button, it becomes very crucial inside a form. 
If your form has multiple buttons, any one of the buttons click will trig submit button hence submit the form.

File: packages/button/src/button.tsx (hunk 1 above)
Comment (segunadebayo) [reply packages/button/src/button.tsx]: I've updated the code to allow the user-defined `type` attribute to win. The reason we added a tagName check is to ensure we don't have `type="button"` to an element that isn't a button.

Technically, it is the work of the user to pass the correct type but since we're setting an internal default type of "button", it's up to us to ensure we don't add that to a non-button element.

Typical example: `<Button as="a">` should not have our internal `type=button` default attribute.

**Review by segunadebayo — APPROVED** [review]
With the recent update I made, this should be good to go.

**Review by TimKolberger — APPROVED** [review]

**Review by with-heart — APPROVED** [review]
I updated the changeset text slightly to be a little more clear for the changelog. 

Looks great though @antoniel! Thanks for taking the time to investigate this and work with us to resolve the bug.

**Comment by with-heart** [comment]
@allcontributors please add @antoniel for code
